name: deploy

on:
  push:
    tags:
    - '*'

jobs:
  pypi:
    strategy:
      matrix:
        distribution: [bdist_wheel, sdist]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.10'
      - name: Package
        run: |
          pip install --upgrade setuptools wheel
          python setup.py ${{ matrix.distribution }}
      - name: Publish
        uses: pypa/gh-action-pypi-publish@v1.0.0a0
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
